[package]
name = "world_server"
version = "0.1.0"
authors = ["lcdr"]
edition = "2018"
license = "AGPL-3.0-or-later"
repository = "https://github.com/lcdr/world_server/"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
minreq = { version = "2.1.1", features = ["https"] }
libsqlite3-sys = { version = "0.20.1", features = ["bundled"] }
diesel = { version = "1.4.6", features = ["sqlite"] }
lu_packets = { git = "https://github.com/lcdr/lu_packets", rev = "7c86c784d763e8653d6b38022b1c44add9b5c32e" }
base_server = { git = "https://github.com/lcdr/base_server", rev = "a7657eff82bfafbf1c19c0a09d1030bd862bacb6", features=[], default-features=false }
rusqlite = "0.24.2"
