[package]
name = "world_server"
version = "0.1.0"
authors = ["lcdr"]
edition = "2018"
license = "AGPL-3.0-or-later"
repository = "https://github.com/lcdr/world_server/"

[dependencies]
minreq = { version = "2.1.1", features = ["https"] }
libsqlite3-sys = { version = "0.9.1", features = ["bundled"] }
diesel = { version = "1.4.3", features = ["sqlite"] }
lu_packets = { git = "https://github.com/lcdr/lu_packets", rev = "92331a88930b884db093bb4dc683ddd8d8de7c3e" }
base_server = { git = "https://github.com/lcdr/base_server", rev = "541e796b76c323cc8a0107bade048514a0b26d14" }
